### ISSUE TITLE
Clean UP & Dockerization eos2hbd

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos2hbd#5]
Please check that the model is working and refactor it model to the latest eos-template structure.
The workflows have already been updated, you can start by checking if the Actions have run successfully or changes need to be made

**Comment by simrantan** [comment]
**Goals/Reflection 6/22** 
(writing towards the mid/end of workday since I want to reflect on what I actually achieve day to day so I can set an accurate amount tasks for upcoming days)
-The model is currently failing. I have been analyzing the log and found that it is not producing an output due to a "unable to open x server" error and there are some "commands not found" in predict.py
-reading through the code to identify error lines, attempting fixes and testing solutions
-ran into trouble trying to test on docker, says permission denied (in docker desktop, the image does not exist when searching for it though actions says this model has been successfully uploaded)

-I am continuing to work on things - I have been stuck at various points today with applications and commands failing + debugging so I hope to achieve more concrete results in future days!

**More details on the model failure:**
This model predicts compound permeability. It still has a training folder that adds extra weight (wanted to check if this should be removed)
The model successfully uploades to Docker and S3 (although it does not appear when searched for in docker...)
The error occurs in the model test during the predict output phase. The exact error is below:
<img width="759" alt="image" src="https://github.com/ersilia-os/eos2hbd/assets/96899862/56e2903f-908e-47ef-87ed-bae64b3adf30">
The lines (6 and 7) are about rdkit so it could be that rdkit is not imported/imported properly causing these "commands not found" error. I am still investigating the server error. 
<img width="342" alt="image" src="https://github.com/ersilia-os/eos2hbd/assets/96899862/dec5a8d8-eab0-4512-a49e-0dedfbf46e1a">

**Comment by GemmaTuron** [comment]
Hi @simrantan,

If you check the Actions of the repository, the model test has failed, therefore the docker and S3 uploads are skipped. 
I suggest cloning the repository and trying the fetch from` --repo_path`, collecting the whole log file and there we will probably have more information about the error to start fixing it.

**Comment by simrantan** [comment]
RESOLVED: - i figured it out, I was using it out of order
Thank you for the tip! I'm unsure how to fetch using --repo-path (I've been using some online resources but their methods seem unapplicable/not correct for this use case). Would you mind giving an example of how I could do that to collect the log file?

**Comment by simrantan** [comment]
I think I may have found the source of the rdkit issue - I looked at a model that also requires rdkit, and saw this difference:
this is eos2hbd -
<img width="424" alt="image" src="https://github.com/ersilia-os/eos2hbd/assets/96899862/3488c8e2-d44b-44df-ab9e-bbf175a06b2b">

and this model eos9ei3, which also uses has rdkit and does not have rdkit conflicts/package conflicts 
<img width="442" alt="image" src="https://github.com/ersilia-os/eos2hbd/assets/96899862/917e0e40-b08c-41df-86ac-bf7356e8d4ed">

After looking at the log of eos2hbd and seeing that a lot of the errors seem to be around conflicts with rdkit, I think changing the conda install to a disable-pip version check install could help?

Also, after running --repo_path on the local version, the model stops running at this point: 
<img width="542" alt="image" src="https://github.com/ersilia-os/eos2hbd/assets/96899862/3e653e64-2630-4a0a-8b84-282835f758ee">

Which is the same location at which all of the rdkit conflicts start being reported in github actions. I've been looking through all of the code for the model and cannot find where I can change this command line arg and see if it helps- any guidance on where to locate these files would be great!

**Comment by GemmaTuron** [comment]
Hi @simrantan, good job!
A few pointers:
- Please do not paste images in the issues, copy the code and add it here so that is more easily readable - if someone needs to copy a line to check on google or elsewhere is much easier, and text is more readable ;)
- To get more information, clone the model in your local system, and try the fetch from repo_path and collect the log file (instructions in the documentation)
- Good check on comparing with other models, but just a note; different models will have very different version requirements depending on the dependencies, the fact that one version works in one model does not mean it will work in another. In any case, if you do want to compare installations between models always refer to the Dockerfile

**Comment by GemmaTuron** [comment]
If possible because the versions are compatible, I'd favour one of the newer rdkit installs that can be installed from pip instead of conda.
You can try to reproduce the environment manually (`conda create -n ...`and then install the different requirementS) and try running the model from run.sh

**Comment by simrantan** [comment]
Thank you for the pointers!! I will make sure to copy code for the future 
-and thank you for the tip, I tried a few different iterations and the newest rdkit installation did work in the local tests I ran on CLI the model was successfully fetched and produced an output! 
Now that it works I am working on the rest of the edits and will have the model ready for testing soon!
